config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
  }
  devise_for :customers, :controllers => {
    :registrations => 'public/registrations',
    :sessions => 'public/sessions',
    :omniauth_callbacks => 'public/omniauth_callbacks',
  }

  scope module: :public do
    root to: 'posts#index'
    get '/search' => 'search#search'
    get '/about' => 'homes#about'
    get '/contact' => 'homes#contact'
    get '/contact/:id' => 'homes#contact_show', as: :contact_show

    resources :posts, except: [:edit, :index] do
      resources :post_ansewers, except: [:index, :new, :show] do
        resources :replys, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end

    get '/best_ansewr_ranking' => 'best_ansewers#ranks_all'
    get '/best_ansewr_ranking_week' => 'best_ansewers#ranks_week'

    resources :customers, except: [:new, :create, :index] do
      member do
        get 'unsubscribe'
        patch 'withdraw'
        get 'ansewers'
        get 'post_index'
      end
    end
  end

  namespace :admin do
    patch '/customers/:id/withdraw' => 'customers#withdraw'
    get '/search' => 'search#search'
    resources :customers, only: [:index, :show, :edit, :update]

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_ansewers, only: [:destroy]
    end

    resources :contact, except: [:new]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :posts, dependent: :destroy
  has_many :ansewers, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image

  validates :info, length: { maximum: 100 }
  validates :nickname, length: { in: 1..10 }
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true

  # コールバック時に呼び出されるメソッド
  def self.find_for_oauth(auth)
    customer = Customer.where(uid: auth.uid, provider: auth.provider).first

    customer ||= Customer.create(
      first_name: auth.info.first_name,
      last_name: auth.info.last_name,
      first_name_kana: "未記入(姓)",
      last_name_kana: "未記入(名)",
      nickname: auth.info.name,
      uid: auth.uid,
      provider: auth.provider,
      # メールアドレス認証もしている為何かしら値が無くてはいけないので仮の値を代入
      email: Customer.dummy_email(auth),
      # ランダムに決まった数字20桁のパスワードを生成
      password: Devise.friendly_token[0, 20]
    )

    customer
  end

  # 会員検索機能
  def self.search_for(selected, content, method)
    if selected == "nickname"
      if method == 'perfect'
        Customer.where(nickname: content)
      elsif method == 'forward'
        Customer.where('nickname LIKE ?', content + '%')
      elsif method == 'backward'
        Customer.where('nickname LIKE ?', '%' + content)
      else
        Customer.where('nickname LIKE ?', '%' + content + '%')
      end
    else
      if method == 'perfect'
        Customer.where(info: content)
      elsif method == 'forward'
        Customer.where('info LIKE ?', content + '%')
      elsif method == 'backward'
        Customer.where('info LIKE ?', '%' + content)
      else
        Customer.where('info LIKE ?', '%' + content + '%')
      end
    end
  end

  # 会員退会処理
  def active_for_authentication?
    super && (is_delete == false)
  end

  # 会員退会、復旧のステータス
  def customer_status_by?(customer)
    Customer.where(id: customer.id, is_delete: true).exists?
  end

  def self.dummy_email(auth)
    # uidとproviderの組み合わせが一意な為こちらを利用
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).reverse_order.per(4)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    current_admin && !current_customer
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customer_path(@customer)
    else
      flash[:alert] = "会員情報を更新に失敗しました。"
      render :edit
    end
  end

  def withdraw
    current_admin && !current_customer
    @customer = Customer.find(params[:id])
    if @customer.is_delete == false
      @customer.update(is_delete: true)
      flash[:alert] = "会員を強制退会させました。"
    else
      @customer.update(is_delete: false)
      flash[:notice] = "会員情報を復旧させました。"
    end
    redirect_to admin_customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(
      :nickname, :email, :last_name, :first_name, :last_name_kana,
      :first_name_kana, :profile_image, :info
    )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_customer_index.html.erb
<% if customers.empty? %>
  <h1 class="text-center text-danger mt-5 pt-5">ユーザーが見つかりませんでした <i class="fas fa-sad-tear"></i></h1>
<% else %>
  <table class="table text-center">
    <thead>
      <tr>
        <th style="width: 100px;">会員ID</th>
        <th>会員画像</th>
        <th>会員名（ニックネーム）</th>
        <th>会員名（本名）</th>
        <th></th>
      </tr>
    </thead>
    <% customers.each do |customer| %>
      <tbody>
        <tr>
          <td><%= customer.id %></td>
          <td><%= attachment_image_tag(customer, :profile_image, size: "50x50", fallback: "no_image.jpg") %></td>
          <td>
            <%= customer.nickname %>
          </td>
          <td>
            <%= "#{customer.last_name} #{customer.first_name}" %><br>
            <%= "(#{customer.last_name_kana} #{customer.first_name_kana})" %>
          </td>
          <td>
            <%= link_to "会員詳細", admin_customer_path(customer), class: "btn btn-primary" %>
            <% if customer.customer_status_by?(customer) %>
              <%= link_to "会員情報復旧", admin_path(customer),method: :patch, class: "btn btn-success", data: { confirm: '会員情報を復旧させますか？' } %>
            <% else %>
              <%= link_to "強制退会", admin_path(customer),method: :patch, class: "btn btn-danger", data: { confirm: '会員を強制退会させますか？' } %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% end %>

app/views/admin/customers/_customer_show.html.erb
<% if customer.posts.blank? %>
  <h1 class="text-danger text-center mt-5 col-12"><%= customer.nickname %>の投稿はまだありません。</h1>
<% else%>
  <% posts.each do |post| %>
    <h4 class="mt-3 ansewer-name">
      「<%= link_to "#{post.title}（←クリックして詳細へ）", admin_post_path(post) %>」
    </h4>
    <table class="table col-12 ext-center">
      <thead>
        <tr>
          <th>
            <h6>投稿日</h6>
          </th>
          <th>
            <h6>投稿回数</h6>
          </th>
          <th>
            <h6>いいね数</h6>
          </th>
          <th>
            <h6>質問ステータス</h6>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= post.created_at.strftime('%Y/%m/%d')%>
          </td>
          <td>
            <%= post.ansewers.where(parent_id: nil).count %>
          </td>
          <td>
            <%= post.favorites.count %>
          </td>
          <td>
            <% if post.best_ansewer.present? %>
              <span class="text-success">解決済み</span>
            <% else %>
              <span class="text-danger">回答募集中</span>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/admin/customers/edit.html.erb
<main class="admin_customer_bg">
  <h1 class="heading text-center">会員情報編集</h1>
  <div class="container admin-text">
    <%= form_with model:@customer,url: admin_customer_path(@customer), local:true do |f| %>
    <div class="row d-flex justify-content-center">
        <div class="field">
          <%= f.label :nickname, "ニックネーム（最大１０字）" %><br>
          <%= f.text_field :nickname, placeholder: "（例）レミ" %>
        </div>
        <div class="field offset-2">
          <%= f.label :email, "メールアドレス" %><br>
          <% if @customer.provider == "google_oauth2" %>
            <p class="text-danger">:現在Googleログインの為<br>変更できません</p>
          <% else %>
            <%= f.text_field :email, placeholder: "(例)XXXXXX@google.com" %>
          <% end %>
        </div>

    </div>

    <div class="row d-flex justify-content-center">
      <div class="customer-field">
        <%= f.label :last_name, "姓" %><br>
        <%= f.text_field :last_name, placeholder: "（例）令和" %>
      </div>
      <div class="customer-field  offset-2">
        <%= f.label :first_name, "名" %><br>
        <%= f.text_field :first_name, placeholder: "（例）道子" %>
      </div>
    </div>

    <div class="row d-flex justify-content-center">
      <div class="field">
        <%= f.label :last_name_kana, "(姓)-カタカナ" %><br>
        <%= f.text_field :last_name_kana, placeholder: "（例）レイワ" %>
      </div>
        <div class="field offset-2">
        <%= f.label :first_name_kana, "(名)-カタカナ" %><br>
        <%= f.text_field :first_name_kana, placeholder: "（例）ミチコ" %>
      </div>
    </div>
    <div class="row mt-5">
    <div class="customer-field offset-4">
      <%= f.label :profile_image, "プロフィール画像" %><br>
      <%= f.attachment_field :profile_image %>
    </div>
    </div>


    <div class="row mt-4">
      <div class="field-body col text-center">
        <%= f.label :info, "紹介文（最大１００字）" %><br>
        <%= f.text_area :info, rows:'3',placeholder: "紹介文を入力してください" %>
      </div>
    </div>

    <div class="actions text-center mt-4">
      <%= f.submit '会員情報更新', class: "btn btn-warning font-italic" %>
    </div>
    <% end %>
  </div>
</main>

app/views/admin/customers/index.html.erb
<% if @path.is('search#search') %>
  <h3 class="serched"><%= "[#{@selected}] を「#{@content}」で検索の結果" %></h3>
<% end %>
<main class="admin_customer_bg">
  <h1 class="admin-text text-center">会員一覧ページ</h1>
  <div id="admin-customer-index">
    <%= render 'admin/customers/customer_index', customers: @customers %>
  </div>
  <div class="kaminari-btn"><%= render "layouts/kaminari", model: @customers %></div>
</main>

app/views/admin/customers/index.js.erb
$('#admin-customer-index).html("<%= j(render 'admin/customers/customer_index', customers: @customers) %>");
$('.kaminari-btn').html("<%= j(render 'layouts/kaminari', model: @customers) %>");

app/views/admin/customers/show.html.erb
<main class="admin_customer_bg">
  <h1 class="admin-text">会員詳細ページです</h1>
  <div class="container-fluid">
    <div class="row">
      <div class="col-3 d-flex justify-content-center">
        <%= attachment_image_tag(@customer, :profile_image, size: "270x270", fallback: "no_image.jpg")%>
      </div>
      <div class="col-9">
        <div class="row">
          <div class="col-11">
            <table class="table table-bordered text-center">
              <thead>
                <tr>
                  <th>ニックネーム</th>
                  <th>本名</th>
                  <th>メールアドレス</th>
                  <th>登録日</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @customer.nickname %></td>
                  <td>
                    <%= @customer.last_name%> <%= @customer.first_name %><br>
                    (<%= @customer.last_name_kana %> <%= @customer.first_name_kana %>)
                  </td>
                  <td>
                    <% if @customer.provider == "google_oauth2" %>
                      <p> Googleログイン中</p>
                    <% else %>
                      <%= @customer.email %>
                    <% end %>
                  </td>
                  <td><%= @customer.created_at.strftime('%Y/%m/%d (%H時%M分)') %></td>
                </tr>
              </tbody>
            </table>
            <table class="table col-12">
              <tr>
                <tbody>
                  <td>
                    <% if @customer.info.nil? %>
                      <p class="py-4 text-center">紹介文の記入はありません。</p>
                    <% else %>
                      <p class="py-4 text-center"><%= @customer.info %></p>
                    <% end %>
                  </td>
                </tbody>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-12 text-center"><%= link_to "会員情報編集", edit_admin_customer_path(@customer), class: "btn btn-success" %>
        <% if @customer.customer_status_by?(@customer) %>
          <%= link_to "会員情報復旧", admin_path(@customer),method: :patch, class: "btn btn-success", data: { confirm: '会員情報を復旧させますか？' } %>
        <% else %>
          <%= link_to "強制退会", admin_path(@customer),method: :patch, class: "btn btn-danger", data: { confirm: '会員を強制退会させますか？' } %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" id="admin-customer-show">
      <%= render "admin/customers/customer_show",customer: @customer, posts: @posts %>
    </div>
  </div>
  <div class="kaminari-btn"><%= render "layouts/kaminari", model: @posts %></div>
</main>

app/views/admin/customers/show.js.erb
$('#admin-customer-show').html("<%= j(render 'admin/customers/customer_show',customer: @customer, posts: @posts) %>");
$('.kaminari-btn').html("<%= j(render 'layouts/kaminari', model:  @posts) %>");