config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
  }
  devise_for :customers, :controllers => {
    :registrations => 'public/registrations',
    :sessions => 'public/sessions',
    :omniauth_callbacks => 'public/omniauth_callbacks',
  }

  scope module: :public do
    root to: 'posts#index'
    get '/search' => 'search#search'
    get '/about' => 'homes#about'
    get '/contact' => 'homes#contact'
    get '/contact/:id' => 'homes#contact_show', as: :contact_show

    resources :posts, except: [:edit, :index] do
      resources :post_ansewers, except: [:index, :new, :show] do
        resources :replys, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end

    get '/best_ansewr_ranking' => 'best_ansewers#ranks_all'
    get '/best_ansewr_ranking_week' => 'best_ansewers#ranks_week'

    resources :customers, except: [:new, :create, :index] do
      member do
        get 'unsubscribe'
        patch 'withdraw'
        get 'ansewers'
        get 'post_index'
      end
    end
  end

  namespace :admin do
    patch '/customers/:id/withdraw' => 'customers#withdraw'
    get '/search' => 'search#search'
    resources :customers, only: [:index, :show, :edit, :update]

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_ansewers, only: [:destroy]
    end

    resources :contact, except: [:new]
  end
end

app/controllers/admin/post_ansewers_controller.rb
class Admin::PostAnsewersController < ApplicationController
  def destroy
    @post = Post.find(params[:post_id])
    if Ansewer.find_by(id: params[:id], post_id: params[:post_id]).destroy
    else
      flash[:alert] = "削除に失敗しました。"
      redirect_to admin_post_path(params[:post_id])
    end
  end
end

app/helpers/admin/post_ansewers_helper.rb
module Admin::PostAnsewersHelper
end

app/views/admin/post_ansewers/_ansewer_index.html.erb
<% if post.ansewers.blank? %>
  <p class="text-center text-danger mt-5 pt-5">まだ回答はありません。</p>
<% end %>
<% post.ansewers.each do |ansewer| %>
  <% if ansewer.parent_id.present? %>
    <% next %>
  <% end %>
  <% if post.best_ansewer == ansewer.id %>
    <h4 class="mt-3">
      <%= link_to admin_customer_path(post.customer) do %>
        <span class="best_ansewer"><%= ansewer.customer.nickname %>さんの回答がベストアンサーです</span>
      <% end %>
    </h4>
  <% else %>
    <h4 class="mt-3">
      <%= link_to admin_customer_path(post.customer) do %>
        <span class="ansewer-name"><%= ansewer.customer.nickname %> さんの回答</span>
      <% end %>
    </h4>
  <% end %>
  <table class="table table-bordered col-12">
    <tbody>
      <tr class="border text-center">
        <td class="py-4">
          「<%= ansewer.body %>」
        </td>
        <td>
          <% if current_admin  %>
            <%= link_to "回答削除", admin_post_post_ansewer_path(ansewer.post_id, ansewer), class: "btn btn-outline-danger", method: :delete, remote: true, data: { confirm: '回答を削除しますか？' } %>
          <% end %>
        </td>
      </tr>
      <% ansewer.replies.order(:created_at).each do |reply| %>
        <tr>
          <td>
            <%= link_to customer_path(reply.customer) do %>
              <span class="bg-light text-dark">[<%= reply.customer.nickname %>]</span><br>
            <% end %>
            <p class="text-center">「<%= reply.body %>」</p>
          </td>
          <% if current_admin %>
            <td class="text-center">
              <%= link_to "返信削除", admin_post_post_ansewer_path(ansewer.post_id, reply), class: "btn btn-outline-danger", method: :delete, remote: true, data: { confirm: '返信を削除しますか？' } %>
            </td>
          <% else %>
          <td></td>
          <% end %>
        </tr>
      <% end %>

    </tbody>
  </table>
<% end %>

app/views/admin/post_ansewers/destroy.js.erb
$('#admin-ansewers').html("<%= j(render 'admin/post_ansewers/ansewer_index', post: @post) %>");
$('#flash-message').html("<%= j(render 'layouts/flash').fadeOut('slow')", 3000 %>");