config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
  }
  devise_for :customers, :controllers => {
    :registrations => 'public/registrations',
    :sessions => 'public/sessions',
    :omniauth_callbacks => 'public/omniauth_callbacks',
  }

  scope module: :public do
    root to: 'posts#index'
    get '/search' => 'search#search'
    get '/about' => 'homes#about'
    get '/contact' => 'homes#contact'
    get '/contact/:id' => 'homes#contact_show', as: :contact_show

    resources :posts, except: [:edit, :index] do
      resources :post_ansewers, except: [:index, :new, :show] do
        resources :replys, only: [:create, :destroy]
      end
      resource :favorites, only: [:create, :destroy]
    end

    get '/best_ansewr_ranking' => 'best_ansewers#ranks_all'
    get '/best_ansewr_ranking_week' => 'best_ansewers#ranks_week'

    resources :customers, except: [:new, :create, :index] do
      member do
        get 'unsubscribe'
        patch 'withdraw'
        get 'ansewers'
        get 'post_index'
      end
    end
  end

  namespace :admin do
    patch '/customers/:id/withdraw' => 'customers#withdraw'
    get '/search' => 'search#search'
    resources :customers, only: [:index, :show, :edit, :update]

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_ansewers, only: [:destroy]
    end

    resources :contact, except: [:new]
  end
end

app/views/layouts/_flash.html.erb
<% if notice %>
	<div class="flash notice">
	  <span class="text-success"><%= notice %></span>
	</div>
<% elsif flash[:success] %>
	<div class="flash success">
	  <% flash[:success]="ログインしました" %>
  	<span class="text-success"><%= flash[:success] %></span>
	</div>
<% elsif flash[:alert] %>
	<div class="flash danger">
	  <span class="text-danger"><%= flash[:alert] %></span>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p><%= link_to "@Outlet Post", about_path %></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% if admin_signed_in? %>
    <div class="header-container">
      <div class="logo">
        <%= link_to "Outlet Post", admin_customers_path %>
      </div>
      <nav>
        <ul class="nav">
          <li class="nav-list"><%= link_to "お知らせ", admin_contact_index_path %></li>
          <li class="nav-list"><%= link_to "Outlet一覧", admin_posts_path %></li>
          <li class="nav-list"><%= link_to "会員一覧", admin_customers_path %></li>
          <li class="nav-list"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
        </ul>
      </nav>
    </div>
  <% elsif customer_signed_in? %>
    <div class="header-container">
    <div class="logo">
      <%= link_to "Outlet Post", root_path %>
    </div>
    <nav>
      <ul class="nav">
        <li class="nav-list"><%= link_to "ランキング", best_ansewr_ranking_path %></li>
        <li class="nav-list"><%= link_to "Outlet Post", new_post_path %></li>
        <li class="nav-list"><%= link_to "Outlet一覧", root_path %></li>
        <li class="nav-list"><%= link_to "マイページ", customer_path(@my_customer) %></li>
        <li class="nav-list"><%= link_to "お知らせ", contact_path %></li>
        <li class="nav-list"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
      </ul>
    </nav>
  </div>
  <% else %>
    <div class="header-container">
      <div class="logo">
        <%= link_to "Outlet Post", root_path %>
      </div>
      <nav>
        <ul class="nav">
          <li class="nav-list"><%= link_to "About", about_path %></li>
          <li class="nav-list"><%= link_to "お知らせ", contact_path %></li>
          <li class="nav-list"><%= link_to "Outlet一覧", root_path %></li>
          <li class="nav-list"><%= link_to "新規登録", new_customer_registration_path %></li>
          <li class="nav-list"><%= link_to "ログイン", new_customer_session_path %></li>
      </nav>
    </div>
  <% end %>
</header>

app/views/layouts/_kaminari.html.erb
<%= paginate model, class: "text-center", remote: true %>

app/views/layouts/_search.html.erb
<% if @path.is('public/posts#index', 'public/search#search') %>
  <div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :selected, options_for_select({ "タイトルで検索" => "title", "本文で検索" => "content" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  </div>
  <% end %>
<% elsif @path.is('admin/posts#index', 'admin/search#search','admin/customers#index') %>
  <div class="search-form">
    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content %>
      <%= f.select :selected, options_for_select({ "タイトルで検索" => "title", "本文で検索" => "content", "ニックネームで検索" => "nickname", "紹介文で検索" => "info" }) %>
      <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OutletPost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="sticky-top">
      <%= render 'layouts/header'%>
      <div id="flash-message"><%= render 'layouts/search'%></div>
      <%= render 'layouts/flash'%>
    </div>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>